#!/bin/bash
#
## Internal Required Variables. (DO NOT CHANGE!)
get_dir () {
     SOURCE="${BASH_SOURCE[0]}"
     while [ -h "$SOURCE" ]; do
          DIRECTORY="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
          SOURCE="$( readlink "$SOURCE" )"
          [[ $SOURCE != /* ]] && SOURCE="$DIRECTORY/$SOURCE"
     done
     DIRECTORY="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
     echo "$DIRECTORY"
}
DIR=$(get_dir)
source $DIR/src/initialize
sym_check;
#############################################################
## User Adjustable Variables. - For More info please read  ##
##   the README.txt in the modules folder.                 ##
#############################################################

INTERFACE=eth0
AUTOREBOOT=NO

# Future Debugging Variables
#DEBUG=1
#LOGFILE=~/logs/netup.log

# Future Debuggin Logfiles..
#function debug() {
#	printf 'DEBUG: '
#}

# Check OS type.
os_check;
# Check if anything needs installed.
print_status "Checking for dependencies..";
check_dep;
check_good "Done!";
# Start NET-UP
print_notification "Starting Net-UP Core..";
run_netup;
check_good "Net-UP Core has finished..";
exit
