echo -e "";
echo -e "\e[1;31m    ███╗   ██╗███████╗████████╗   ██╗   ██╗██████╗ ";
echo -e "\e[1;31m    ████╗  ██║██╔════╝╚══██╔══╝   ██║   ██║██╔══██╗";
echo -e "\e[1;31m    ██╔██╗ ██║█████╗     ██║█████╗██║   ██║██████╔╝";
echo -e "\e[1;31m    ██║╚██╗██║██╔══╝     ██║╚════╝██║   ██║██╔═══╝ ";
echo -e "\e[1;31m    ██║ ╚████║███████╗   ██║      ╚██████╔╝██║     ";
echo -e "\e[1;31m    ╚═╝  ╚═══╝╚══════╝   ╚═╝       ╚═════╝ ╚═╝     ";
echo -e "                                                           ";
echo -e "\e[1;92m                  Version $VERS                    ";
echo -e "\e[1;96m      A Network-Based Startup Module Framework     ";
echo -e "\e[1;94m            GPL Licensed to InfoSecREDD            ";
echo -e "\e[1;94m          https://github.com/InfoSecREDD           ";
echo "";
