echo -e "";
echo -e "\e[1;31m    ███╗   ██╗███████╗████████╗   ██╗   ██╗██████╗ ";
echo -e "\e[1;31m    ████╗  ██║██╔════╝╚══██╔══╝   ██║   ██║██╔══██╗";
echo -e "\e[1;31m    ██╔██╗ ██║█████╗     ██║█████╗██║   ██║██████╔╝";
echo -e "\e[1;31m    ██║╚██╗██║██╔══╝     ██║╚════╝██║   ██║██╔═══╝ ";
echo -e "\e[1;31m    ██║ ╚████║███████╗   ██║      ╚██████╔╝██║     ";
echo -e "\e[1;31m    ╚═╝  ╚═══╝╚══════╝   ╚═╝       ╚═════╝ ╚═╝     ";
echo -e "                                               ";
echo -e "\e[1;92m                  Version $VERS                ";
echo -e "\e[1;96m      A Network-Based Startup Module Framework   ";
echo -e "\e[1;94m        GPL Licensed to Private-Locker & REDD    ";
echo -e "\e[1;94m          https://github.com/private-locker      ";
echo "";
