#!/usr/bin/env bash
source $DIR/etc/vers
source $DIR/etc/auth.mk
start_notice(){
    echo -e "\x1B[01;33m[!]\x1B[0m $1"
}
start_notice "Initializing Functions & Variables..";
source $DIR/src/sys_vars
source $DIR/src/misc
source $DIR/src/init.sh
if [ ! -f $DIR/.conf ]; then
        source $DIR/src/symchk.sh
        source $DIR/src/checkdep.sh
        source $DIR/src/oscheck.sh
        sym_check;
        os_check;
        check_dep;
fi
source $DIR/src/updatemodules
source $DIR/src/update
source $DIR/src/cron
source $DIR/src/chkconn.sh
source $DIR/src/core
BREAK=$(do_break)
SLEEP=$(do_sleep)
