#!/usr/bin/env bash
# Module Update
updategithub(){
        echo -e "";
        print_status "Update/sync with Private-Locker's GitHub?";
        echo -e "";
		print_error "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";
        print_error "!! THIS WILL REMOVE YOUR ENTIRE NET-UP DIRECTORY !!";
		print_error "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";
        echo -e "";
        read -p " Are you sure? [Y/n]" -n 1 -r
        echo -e "";
        if [[ $REPLY =~ ^[Yy]$ ]]; then
                print_status "Removing Old NET-UP Directory..";
				cd $HOME;
                rm -rf $HOME/netup;
                echo -e "";
                git clone $GITHUBREPO netup
				chmod +x $HOME/netup/netup;
				cd $HOME/netup
				rm -rf $HOME/netup/modules
			    git clone $MODULEREPO $HOME/netup/modules
				chmod +x $HOME/netup/modules/disablemod
				chmod +x $HOME/netup/modules/enablemod
                echo -e "";
                print_status "Entire NET-UP was synced to Private-Locker's Repo including Modules.";
				echo -e "";
				print_error "Removing install script.";
				rm -rf $HOME/netup/install.sh
				touch $HOME/netup/.conf
				echo -e "";
				cd;

        else
                echo -e ""
				print_status "Not Updating NET-UP Framework. Exiting.";

		fi
}
fastupdategithub() {
                print_status "Removing Old NET-UP Directory..";
                                cd $HOME;
                rm -rf $HOME/netup;
                echo -e "";
                git clone $GITHUBREPO $HOME/netup
                                chmod +x $HOME/netup/netup;
                                cd $HOME/netup
                                rm -rf $HOME/netup/modules
                            git clone $MODULEREPO $HOME/netup/modules
                                chmod +x $HOME/netup/modules/disablemod
                                chmod +x $HOME/netup/modules/enablemod
                echo -e "";
                print_status "Entire NET-UP was synced to Private-Locker's Repo including Modules.";
                                echo -e "";
                                print_error "Removing install script.";
                                rm -rf $HOME/netup/install.sh
                                touch $HOME/netup/.conf
                                echo -e "";
                                cd;

}
