#!/usr/bin/env bash
# Module Update
updategithub(){
        echo -e "";
        print_status "Update/sync with Private-Locker's GitHub?";
        echo -e "";
        print_error "THIS WILL REMOVE YOUR ENTIRE NET-UP DIRECTORY!";
        echo -e "";
        read -p " Are you sure? [Y/n]" -n 1 -r
        echo -e "";
        if [[ $REPLY =~ ^[Yy]$ ]]; then
                print_status "Removing Old NET-UP Directory..";
				cd;
                rm -rf netup;
                echo -e "";
                git clone $GITHUBREPO netup
				chmod +x netup/netup;
				cd netup
				rm -rf modules
			    git clone $MODULEREPO modules
				chmod +x modules/disablemod
				chmod +x modules/enablemod
                echo -e "";
                print_status "Entire NET-UP was synced to Private-Locker's Repo including Modules.";
				echo -e "";
				print_error "Removing install script.";
				rm -rf netup/install.sh
				echo -e "";
        else
                print_status "Not Updating NET-UP.";
        fi
}