name: Check Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Checking Core of NET-UP
      run: bash .github/workflows/checkbuild.sh
      shell: bash
